spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: itoken-zuul
      label: master
      profile: dev

zool:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itoken-client