spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      uri: http://localhost:8888
      name: itoken-zuul
      label: master
      profile: dev